#!/bin/bash

notify-send "Wifi action" "Wifi wil be taken on interface: ${IFACE}"

# If connected to
if [ "$IFACE" == "enx9cebe82c1334" ]; then
  notify-send "Wifi turned on" "Wifi has been turned on as ${IFACE} has been disconnected"
  nmcli radio wifi on
fi
