#!/bin/bash

notify-send "Wifi action" "Wifi wil be taken on interface: ${IFACE}"

# If connected to
if [ "$IFACE" == "enx9cebe82c1334" ]; then
  notify-send "Wifi turned off" "Wifi has been turned of as ${IFACE} has been connected"
  nmcli radio wifi off
fi
